### ISSUE TITLE
MQTT-Topic for machine state

### ISSUE THREAD

**Issue by gang-himself** [rancilio-pid/clevercoffee#293]
I'd love to have the machine-state as mqtt-topic, as this would help to make some automations or statistics in for example homeassistant.
I hope this should be quite easy, as the machine-state is already printed in the debug-console.

Thanks,
Wolfgang

**Comment by murmeltier08** [comment]
We will add it later for the esp32 build.

**Comment by gang-himself** [comment]
Is there a chance to get it also in the ESP8266-Build, as this is the one I‘ve used…

**Comment by murmeltier08** [comment]
i will check it, if it possible

**Comment by Nilaik** [comment]
I created  a pull request how it could be done: https://github.com/rancilio-pid/clevercoffee/pull/300

However, if state changes appear fast it will not publish all of them because the function writeSysParamsToMQTT is not called only at the end of the loop. Sending the machine state could also be added to printMachineState but that felt kind of weird since this function only contains debug prints.

**Comment by murmeltier08** [comment]
Thank you, PR is merged

**Comment by gang-himself** [comment]
Thanks, works as expected.
