### ISSUE TITLE
Brew detection not detecting that the brewing already stopped

### ISSUE THREAD

**Issue by niklasarnitz** [rancilio-pid/clevercoffee#319]
It ran until 200s, I then rebooted the machine.

PID+, so it's temperature based brew detection.

V3.1.1

**Comment by kjyv** [comment]
OnlyPID+ is using hardware to detect the brew switch state. Do you mean OnlyPID with Software brew detection?
You might have to fine tune its parameters to make the detection work better in you case, see the manual.

**Comment by niklasarnitz** [comment]
![Screenshot 2023-01-27 at 12 04 09](https://user-images.githubusercontent.com/24507162/215071403-39470dba-e926-4603-b5a4-b778d93b15f9.png)

**Comment by kjyv** [comment]
So, I've tried to reproduce this with the current version 3.1.2 and could not see anything wrong. First of all, software brew detection does not detect that the brew stopped (it can't really know when that is because the temperature does not do anything obvious when the brew stops), it simply stops after the set time - you have set 120 seconds. If I wait that long, the counter disappears and everything is back to the state it was before. You probably don't want to do any brews that are that long, so 40 or 50 should be enough. With OnlyPID+ or changing the brew switch to a trigger, you can't expect to see accurate time measurements, also the start is always a bit delayed. The only purpose of this is to set different PID parameters during brew, but you also are likely to not need that (depends on the machine type).

**Comment by niklasarnitz** [comment]
Okay, that makes sense.
Sorry for the confusion!
