### ISSUE TITLE
clevercoffee.de is blank

### ISSUE THREAD

**Issue by lassem** [rancilio-pid/clevercoffee#372]
Website only renders a white page.
Tested on MacOS with Chrome and Safari and Chrome on a Pixel 7

**Comment by fiendie** [comment]
Could you hook up the board via USB and copy-paste the output of the serial monitor?

**Comment by chris-dot-exe** [comment]
> Could you hook up the board via USB and copy-paste the output of the serial monitor?

I'm pretty sure @lassem is taking about the website [https://clevercoffee.de/](https://clevercoffee.de/)  not the website served from the ESP cause I also only get a white page since yesterday

![Screenshot_20230925_075437_org mozilla firefox](https://github.com/rancilio-pid/clevercoffee/assets/49272981/240f28af-7b2a-42c2-8975-0f8697850831)

**Comment by fiendie** [comment]
My bad. @btotherunner is running the website and he's looking into it.

**Comment by murmeltier08** [comment]
website is running right now
